In [ ]:
#pip install opencv-python

In [ ]:
import cv2
import numpy as np
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

In [ ]:
img = cv2.imread('images/face0.jpeg')

In [ ]:
gray_picture = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)#make picture gray
faces = face_cascade.detectMultiScale(gray_picture, 1.3, 5)

In [ ]:
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,255,0),2)

cv2.imshow('my image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
gray_face = gray_picture[y:y+h, x:x+w] # cut the gray face frame out
face = img[y:y+h, x:x+w] # cut the face frame out
eyes = eye_cascade.detectMultiScale(gray_face)

In [ ]:
for (ex,ey,ew,eh) in eyes: 
    cv2.rectangle(face,(ex,ey),(ex+ew,ey+eh),(0,225,255),2)

cv2.imshow('my image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Iteración 1
def detect_eyes(img, img_gray, classifier):
    coords = cascade.detectMultiScale(img_gray, 1.3, 5)# detect eyes
    height = np.size(img, 0) # get face frame height
    for (x, y, w, h) in coords:
        if y+h > height/2: # pass if the eye is at the bottom
            pass

In [ ]:
#Iteración 2
def detect_eyes(img, classifier):
    gray_frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    eyes = cascade.detectMultiScale(gray_frame, 1.3, 5) # detect eyes
    width = np.size(img, 1) # get face frame width
    height = np.size(img, 0) # get face frame height
    for (x, y, w, h) in eyes:
        if y > height / 2:
            pass
        eyecenter = x + w / 2  # get the eye center
        if eyecenter < width * 0.5:
            left_eye = img[y:y + h, x:x + w]
        else:
            right_eye = img[y:y + h, x:x + w]
    return left_eye, right_eye

In [ ]:
#Iteración 3
def detect_eyes(img, classifier):
    gray_frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    eyes = classifier.detectMultiScale(gray_frame, 1.3, 5) # detect eyes
    width = np.size(img, 1) # get face frame width
    height = np.size(img, 0) # get face frame height
    left_eye = None
    right_eye = None
    for (x, y, w, h) in eyes:
        if y > height / 2:
            pass
        eyecenter = x + w / 2  # get the eye center
        if eyecenter < width * 0.5:
            left_eye = img[y:y + h, x:x + w]
        else:
            right_eye = img[y:y + h, x:x + w]
    return left_eye, right_eye

In [ ]:
def detect_faces(img, classifier):
    gray_frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    coords = classifier.detectMultiScale(gray_frame, 1.3, 5)
    if len(coords) > 1:
        biggest = (0, 0, 0, 0)
        for i in coords:
            if i[3] > biggest[3]:
                biggest = i
        biggest = np.array([i], np.int32)
    elif len(coords) == 1:
        biggest = coords
    else:
        return None
    for (x, y, w, h) in biggest:
        frame = img[y:y + h, x:x + w]
    return frame

In [ ]:
detector_params = cv2.SimpleBlobDetector_Params()
detector_params.filterByArea = True
detector_params.maxArea = 150
detector = cv2.SimpleBlobDetector_create(detector_params)

In [ ]:
_, img = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

cv2.imshow('my image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
def cut_eyebrows(img):
    height, width = img.shape[:2]
    eyebrow_h = int(height / 4)
    img = img[eyebrow_h:height, 0:width]  # cut eyebrows out (15 px)
    return img

In [ ]:
def blob_process(img, detector):
    _, img = cv2.threshold(img, 42, 255, cv2.THRESH_BINARY)
    img = cv2.erode(img, None, iterations=2)
    img = cv2.dilate(img, None, iterations=4)
    img = cv2.medianBlur(img, 5)
    show_img(img)
    keypoints = detector.detect(img)
    return keypoints

In [ ]:
def main():
    cap = cv2.VideoCapture(cv2.CAP_DSHOW)
    while True:
        _, frame = cap.read()
        face_frame = detect_faces(frame, face_cascade)
        if face_frame is not None:
            eyes = detect_eyes(face_frame, eye_cascade)
            for eye in eyes:
                if eye is not None:
                    eye = cut_eyebrows(eye)
                    keypoints = blob_process(eye, detector)
                    eye = cv2.drawKeypoints(eye, keypoints, eye, (0, 0, 255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
        cv2.imshow('my image', face_frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()      

In [ ]:
def show_img(img, name='my image'):
    cv2.imshow(name,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

def blob_process(img, detector):
    _, img = cv2.threshold(img, 42, 255, cv2.THRESH_BINARY)
    show_img(img,"0")
    img = cv2.erode(img, None, iterations=4)
    show_img(img,"1")
    img = cv2.dilate(img, None, iterations=6)
    show_img(img,"2")
    img = cv2.medianBlur(img, 7)
    show_img(img,"BLOB")
    keypoints = detector.detect(img)
    return keypoints

img = cv2.imread('images/face03.jpg')
face_frame = detect_faces(img, face_cascade)
eyes = detect_eyes(face_frame, eye_cascade)

blob_detector_params = cv2.SimpleBlobDetector_Params()
blob_detector_params.filterByArea = True
blob_detector_params.maxArea = 150
blob_detector = cv2.SimpleBlobDetector_create(blob_detector_params)

for eye in eyes:
    if eye is not None:
        eye = cut_eyebrows(eye)
        keypoints = blob_process(eye, blob_detector)
        print(str(keypoints))
        eye = cv2.drawKeypoints(eye, keypoints, eye, (0, 0, 255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
        show_img(eye)
show_img(face_frame)

In [3]:
def show_img(img, name='my image'):
    cv2.imshow(name,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
#Iteración 3
def detect_eyes(img, classifier):
    gray_frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    eyes = classifier.detectMultiScale(gray_frame, 1.07, 3) # detect eyes
    print("Ojos: ",eyes)
    width = np.size(img, 1) # get face frame width
    height = np.size(img, 0) # get face frame height
    left_eye = None
    right_eye = None
    for (x, y, w, h) in eyes:
        if y > height / 2:
            pass
        eyecenter = x + w / 2  # get the eye center
        if eyecenter < width * 0.5:
            left_eye = img[y:y + h, x:x + w]
        else:
            right_eye = img[y:y + h, x:x + w]
    return left_eye, right_eye
def detect_faces(img, classifier):
    gray_frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    coords = classifier.detectMultiScale(gray_frame, 1.3, 5)
    if len(coords) > 1:
        biggest = (0, 0, 0, 0)
        for i in coords:
            if i[3] > biggest[3]:
                biggest = i
        biggest = np.array([i], np.int32)
    elif len(coords) == 1:
        biggest = coords
    else:
        return None
    for (x, y, w, h) in biggest:
        frame = img[y:y + h, x:x + w]
    return frame
def cut_eyebrows(img):
    height, width = img.shape[:2]
    eyebrow_h = int(height / 5)
    img = img[eyebrow_h:height, 0:width]  # cut eyebrows out (15 px)
    return img
def blob_process(img, detector):
    _, img = cv2.threshold(img, 42, 250, cv2.THRESH_BINARY)
    img = cv2.erode(img, None, iterations=5)
    img = cv2.dilate(img, None, iterations=6)
    img = cv2.medianBlur(img, 7)
    keypoints = detector.detect(img)
    return keypoints

In [ ]:
def show_img(img, name='my image'):
    cv2.imshow(name,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
#Iteración 3
def detect_eyes(img, classifier):
    gray_frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    eyes = classifier.detectMultiScale(gray_frame, 1.07, 3) # detect eyes
    print("Ojos: ",eyes)
    width = np.size(img, 1) # get face frame width
    height = np.size(img, 0) # get face frame height
    left_eye = None
    right_eye = None
    for (x, y, w, h) in eyes:
        if y > height / 2:
            pass
        eyecenter = x + w / 2  # get the eye center
        if eyecenter < width * 0.5:
            left_eye = img[y:y + h, x:x + w]
        else:
            right_eye = img[y:y + h, x:x + w]
    return left_eye, right_eye
def detect_faces(img, classifier):
    gray_frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    coords = classifier.detectMultiScale(gray_frame, 1.3, 5)
    if len(coords) > 1:
        biggest = (0, 0, 0, 0)
        for i in coords:
            if i[3] > biggest[3]:
                biggest = i
        biggest = np.array([i], np.int32)
    elif len(coords) == 1:
        biggest = coords
    else:
        return None
    for (x, y, w, h) in biggest:
        frame = img[y:y + h, x:x + w]
    return frame
def cut_eyebrows(img):
    height, width = img.shape[:2]
    eyebrow_h = int(height / 5)
    img = img[eyebrow_h:height, 0:width]  # cut eyebrows out (15 px)
    return img
def blob_process(img, detector):
    _, img = cv2.threshold(img, 42, 250, cv2.THRESH_BINARY)
    img = cv2.erode(img, None, iterations=5)
    img = cv2.dilate(img, None, iterations=6)
    img = cv2.medianBlur(img, 7)
    keypoints = detector.detect(img)
    #my_testing(keypoints,img)
    return keypoints

def my_testing(keypoints,img):
    if len(keypoints)>0:
        print("========pausa eye:",img.shape)
        kp_coordinate = (0,0)
        kp_size = 0
        for kp in keypoints:
            if kp.size > kp_size:
                kp_size = kp.size
                kp_coordinate = kp.pt
        print("=================Size:",kp_size)
        print("=================coordinate:",kp_coordinate)
        show_img(img,"0")

import cv2
import numpy as np
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

def main():
    blob_detector_params = cv2.SimpleBlobDetector_Params()
    blob_detector_params.filterByArea = True
    blob_detector_params.maxArea = 150
    blob_detector = cv2.SimpleBlobDetector_create(blob_detector_params)
    cap = cv2.VideoCapture(0)
    inas=0
    while True:
        _, frame = cap.read()
        face_frame = detect_faces(frame, face_cascade)
        if face_frame is not None:
            eyes = detect_eyes(face_frame, eye_cascade)
            for eye in eyes:
                if eye is not None:
                    eye = cut_eyebrows(eye)
                    print("=================eyesize:",eye.shape)
                    keypoints = blob_process(eye, blob_detector)
                    if len(keypoints) > 0:
                        keypoints[0].pt = (eye.shape[0]-eye.shape[0]*.05, eye.shape[1]-eye.shape[1]*.1)
                        keypoints[0].size = 15.0
                        show_img(eye,"0")
                    eye = cv2.drawKeypoints(eye, keypoints, eye, (0, 0, 255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
                    if len(keypoints) > 0:
                        show_img(eye,"0")
                    kp_coordinate = (0,0)
                    kp_size = 0
                    for kp in keypoints:
                        if kp.size > kp_size:
                            kp_size = kp.size
                            kp_coordinate = kp.pt
                    print("=================Size:",kp_size)
                    print("=================coordinate:",kp_coordinate)
                    print("Frame:",inas,keypoints)
            inas+=1
            cv2.imshow('showing', face_frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()   
    
def face_scale(frame, objt):
    width = (objt[0])/frame[0]
    height = (objt[1])/frame[1]
    return widht, height
    
def face_position(frame, objt):
    width = (frame[0] - objt[0])/frame[0]
    height = (frame[1] - objt[1])/frame[1]
    return widht, height




In [ ]:
main()

Ojos:  [[ 85 164  24  24]
 [100 111  24  24]
 [114  56  40  40]
 [ 40  57  43  43]]
=================eyesize: (35, 43, 3)
=================Size: 0
=================coordinate: (0, 0)
Frame: 0 []
=================eyesize: (32, 40, 3)
=================Size: 0
=================coordinate: (0, 0)
Frame: 0 []
Ojos:  [[ 87 167  26  26]
 [119  61  37  37]
 [ 47  63  36  36]]
=================eyesize: (29, 36, 3)
=================Size: 0
=================coordinate: (0, 0)
Frame: 1 []
=================eyesize: (30, 37, 3)
=================Size: 15.0
=================coordinate: (28.5, 33.29999923706055)
Frame: 1 [<KeyPoint 000001BA0CBCBC30>]
Ojos:  [[117  53  25  25]
 [ 34  72  23  23]
 [ 42  66  36  36]]
=================eyesize: (29, 36, 3)
=================Size: 0
=================coordinate: (0, 0)
Frame: 2 []
=================eyesize: (20, 25, 3)
=================Size: 0
=================coordinate: (0, 0)
Frame: 2 []
Ojos:  [[118  58  25  25]
 [ 39  69  38  38]]
=================eyesize:

In [ ]:
def blob_process(img, detector):
    _, img = cv2.threshold(img, 42, 255, cv2.THRESH_BINARY)
    show_img(img,"0")
    img = cv2.erode(img, None, iterations=5)
    show_img(img,"1")
    img = cv2.dilate(img, None, iterations=6)
    show_img(img,"2")
    img = cv2.medianBlur(img, 7)
    show_img(img,"BLOB")
    keypoints = detector.detect(img)
    return keypoints